modLoader = "javafml"
loaderVersion = "[26,)"

authors = "chylex"
issueTrackerURL = "https://github.com/chylex/Better-Sprinting/issues"

[[mods]]
modId = "bettersprinting"
version = "2.3.0"
displayName = "Better Sprinting"
displayURL = "https://bsprint.chylex.com"
updateJSONURL = "https://raw.githubusercontent.com/chylex/Better-Sprinting/master/UpdateInfo.json"
description = '''
New sprinting and sneaking functionality. Mod settings are configurable in Controls and in-game menu (default: 'O'), for internal settings (notifications) click Config button below.

Find me on Twitter: https://twitter.com/chylexmc
'''

[[dependencies.bettersprinting]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.14.3]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.bettersprinting]]
    modId = "forge"
    mandatory = true
    versionRange = "[26.0.21,)"
    ordering = "NONE"
    side = "BOTH"
